logo: # add logo name
title: Evan Fung - Enjoy Freedom
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "evanfungv.com" # the base hostname & protocol for your site, e.g. http://example.com

# Banner settings
video: mountains.mp4 # add banner video. Add your video file to the folder video
banner-title: You may say I'm a dreamer # add banner title
banner-desc:  but I'm not the only one - John Lennon # add banner description

# Author settings
author-pic: face.jpg # your photo
author-name: Evan Fung # your name
about-author: |
  I'm a software developer, web enthusiast, and computer science student living in Hong Kong.
email: evanfungv@gmail.com # your email
phone: (852)-不方便透露 # your pnone number
website: https://evanfungv.com # you website

# Social link
google_url:    # add url link
twitter_url:   # add url link
instagram_url: https://www.instagram.com/evan___fung/ # add url link
pinterest_url: # add url link
dribbble_url:  # add url link
facebook_url: https://www.facebook.com/hhhhhao # add url link

# Disqus
discus_identifier: evanfungv-com # add your discus identifier

# Newsletter
mailchimp: evanfungv.us16.list-manage.com/subscribe/post?u=64d41f9524c5e4e1e50994595&amp;id=25a606806d # add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Tracker
analytics: UA-106343822-1

# Paginate
paginate: 12
paginate_path: /page:num/

# Build settings
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
